name: "BIO-wijzigingsverzoek"
description: "Dank je wel voor het indienen van een wijzigingsverzoek"
assignees:
  - Annemieke-CIP
  - BartL-CIP
title: "Geef_een_korte_omschrijving_van_het_wijzigingsverzoek"
labels:
  - wijzigingsvoorstel
body:
  - type: input
    id: bio_version
    attributes:
      label: BIO-versie
      description: Versienummer bijvoorbeeld BIO2 v1.3
      placeholder: "Noteer het versienummer van de BIO waarop het wijzigingsverzoek betrekking heeft"
    validations:
      required: true

  - type: dropdown
    id: welk_deel_van_de_BIO
    attributes:
      label: Welk deel van de BIO
      options:
        - Voortekst
        - Deel 1 BIO2-kader
        - Deel 2 BIO-overheidsmaatregelen
    validations:
      required: true

  - type: input
    id: maatregelen_nummers
    attributes:
      label: Maatregel- en eventueel regelnummer(s)
      placeholder: "Maatregel- en eventueel regelnummer(s)"
    validations:
      required: true

  - type: textarea
    id: huidige_tekst
    attributes:
      label: Huidige tekst
      description: Noteer de huidige tekst.
      render: text
      placeholder: "Noteer de huidige tekst"
    validations:
      required: true

  - type: textarea
    id: voorgestelde_tekst
    attributes:
      label: Voorgestelde tekst
      description: Noteer de voorgestelde tekst.
      render: text
      placeholder: "Noteer de voorgestelde tekst"
    validations:
      required: true

  - type: textarea
    id: argumentatie
    attributes:
      label: Argumentatie
      placeholder: "Noteer de argumenten"
      render: text
    validations:
      required: true

  - type: textarea
    id: verwachte_impact
    attributes:
      label: Verwachte impact
      placeholder: "Noteer de verwachte positieve en negatieve impact"
      render: text

  - type: checkboxes
    id: besluitvraag
    attributes:
      label: Besluitvraag
      options:
        - label: Besluitvorming werkgroep BIO en kennisname kern-IBO indien niet impactvol.
        - label: Besluitvorming kern-IBO en OBDO indien impactvol.
        - label: Publicatie op github.com/bio-overheid na besluit.

  - type: textarea
    id: opmerkingen
    attributes:
      label: Opmerkingen
      placeholder: "Overige toelichting, links en bijlagen"
      render: text
